---
packages:
  voice_assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main
  
esphome:
  name: ${name}
  friendly_name: ${friendly_name}

api:
  encryption:
    key: ${encryption_key}

ota:
  password: ${ota_password}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  manual_ip:
    static_ip: ${ip_adress}
    gateway: ${gateway}
    subnet: ${subnet}
