---
packages:
  voice_assistant:
    url: https://github.com/esphome/firmware
    ref: main
    file: "voice-assistant/m5stack-atom-echo.yaml"
    refresh: 0s
  
esphome:
  name: ${name}
  friendly_name: ${friendly_name}

api:
  encryption:
    key: ${encryption_key}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  manual_ip:
    static_ip: ${ip_address}
    gateway: ${gateway}
    subnet: ${subnet}
